name: Generate Snake Contributions Graph

on:
  schedule:
    - cron: "0 0 * * *"
    - cron: "30 18 * * *"
  workflow_dispatch:
  push:
    branches:
      - dist
      - main

jobs:
  generate-snake:
    name: Generate Snake
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: dist

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            snake/github-contribution-snake.svg
            snake/github-contribution-snake-dark.svg?palette=github-dark
            snake/github-contribution-snake-ocean.svg?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Contributions Snake
          branch: dist
          file_pattern: "snake/*"
