name: Generate Snake Contributions Graph

on:
  schedule:
    - cron: "0 0 * * *"
    - cron: "30 18 * * *"
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  generate-snake:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-snake.svg
            dist/github-contribution-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
